### ISSUE TITLE
usage of ClientSecret is not working

### ISSUE THREAD

**Issue by pentium10** [BingAds/BingAds-PHP-SDK#78] opened 2018-09-04 11:29 UTC
Where is this field being used?

```
final class AuthHelper {
    const ClientSecret = 'ClientSecretGoesHere'; 
```
https://github.com/BingAds/BingAds-PHP-SDK/blob/master/samples/V12/AuthHelper.php#L47

how do we obtain a client secret?

as whatever we setup in here, even if we delete the field, the code works,
and the authorization flow is not working we keep getting:

> Error: invalid_client
> Description: The provided request must include a 'client_secret' input parame
> ter.
>

**Comment by eric-urban** [comment] 2018-09-04 15:12
@pentium10 closing as duplicate of doc issue [368](https://github.com/MicrosoftDocs/BingAds-docs/issues/368).

**Closed by eric-urban** 2018-09-04 15:12 UTC
