### ISSUE TITLE
authorize flow issue in samples

### ISSUE THREAD

**Issue by pentium10** [BingAds/BingAds-PHP-SDK#77] opened 2018-09-02 09:20 UTC
I'm using the most recent version of: ReportRequests.php and changed parameters to Production

when I run this project I get the following url to use in a browser to get a token: 
https://login.live.com/oauth20_authorize.srf?scope=bingads.manage&client_id=b0
d1c26f-889b-4d16-aac1-51864b9cea8c&response_type=code&redirect_uri=https://log
in.live.com/oauth20_desktop.srf

and it gives me this pag,e which is kinda wrong

https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

I am having also problems to get all the correct information from the Developers panel.
We have App ID in the panel, where to use that?
How do we obtain Client ID? IS the client ID above correct format?
How do we obtain Client Secret?
How to use service accounts that don't prompt the user for web token?

**Comment by eric-urban** [comment] 2018-09-04 15:12
@pentium10 closing as duplicate of doc issue [368](https://github.com/MicrosoftDocs/BingAds-docs/issues/368).

**Closed by eric-urban** 2018-09-04 15:12 UTC
